name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # - name: Validate Remote Config
      #   run: npm run remote-config:validate:staging
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_STAGING }}

      - name: Build
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ vars.FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ vars.FIREBASE_MEASUREMENT_ID }}
          VITE_USE_FIREBASE_EMULATOR: ${{ vars.VITE_USE_FIREBASE_EMULATOR }}
          VITE_APP_VERSION: ${{ github.sha }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Setup staging rules
        run: cp firestore.staging.rules firestore.rules

      - name: Deploy to Firebase Staging
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,firestore -P staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_STAGING }}

      - name: Run Smoke Tests on Staging
        run: |
          echo "Waiting for staging to deploy..."
          sleep 30
          npx playwright test tests/e2e/smoke.spec.js --retries=2
        env:
          TEST_URL: https://argbase-staging.web.app

      - name: Run Full E2E Tests on Staging
        run: |
          npx playwright test tests/e2e --retries=2
        env:
          TEST_URL: https://argbase-staging.web.app

      - name: Upload logs on failure
        if: failure()
        run: |
          echo "## Staging Deployment or Tests Failed" >> $GITHUB_STEP_SUMMARY
